### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bart451** [Agora-X/DALLE3-API#8]
**Describe the bug**
What am I doing wrong?
**To Reproduce**
>>> import os
>>> import logging
>>> from dalle3 import Dalle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/dalle3/__init__.py", line 2, in <module>
    from dalle3.idea2image import Idea2Image
  File "/opt/homebrew/lib/python3.11/site-packages/dalle3/idea2image.py", line 5, in <module>
    from swarms.models import OpenAIChat
  File "/opt/homebrew/lib/python3.11/site-packages/swarms/__init__.py", line 13, in <module>
    from swarms.swarms.orchestrate import Orchestrator
  File "/opt/homebrew/lib/python3.11/site-packages/swarms/swarms/__init__.py", line 3, in <module>
    from swarms.swarms.dialogue_simulator import DialogueSimulator
  File "/opt/homebrew/lib/python3.11/site-packages/swarms/swarms/dialogue_simulator.py", line 2, in <module>
    from swarms.workers.worker import Worker
  File "/opt/homebrew/lib/python3.11/site-packages/swarms/workers/__init__.py", line 1, in <module>
    from swarms.workers.worker import Worker
  File "/opt/homebrew/lib/python3.11/site-packages/swarms/workers/worker.py", line 13, in <module>
    from swarms.tools.autogpt import (
  File "/opt/homebrew/lib/python3.11/site-packages/swarms/tools/autogpt.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by iamshaynez** [comment]
need to manually install pandas first. If you are running in a fresh environment like CI, then put pandas in the requiremets.txt will bypass this.

Pkg denpency fix will be better. LOL

**Comment by kyegomez** [comment]
@bart451 I've solved it now, upgrade the package
